; Este é um arquivo de configuração
; Comentários iniciam com ';', como no php.ini

driver = "mysql";
server = "localhost";
user = "aclioo79_ramos";
password = "ramosab847234";
database = "aclioo79_ramos";
port = "3306";
debug = "";