; Este é um arquivo de configuração
; Comentários iniciam com ';', como no php.ini

driver = "mysql";
server = "localhost";
user = "mateusra_dws2_MateusRamos";
password = "Epzd3FzuePHSJXBHbY2t";
database = "mateusra_dws2_MateusRamos";
port = "3306";
debug = "";